// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "HDMrP_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// update_Ci
void update_Ci(int itt, MatrixXd& C_i, MatrixXd& C_prob, const MatrixXd& S_i, const MatrixXd& Z, const MatrixXd& X, const MatrixXd Y, const MatrixXd& alpha, const MatrixXd& beta, const MatrixXd theta, const MatrixXd psi);
RcppExport SEXP HDMrP_update_Ci(SEXP ittSEXP, SEXP C_iSEXP, SEXP C_probSEXP, SEXP S_iSEXP, SEXP ZSEXP, SEXP XSEXP, SEXP YSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP thetaSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type itt(ittSEXP);
    Rcpp::traits::input_parameter< MatrixXd& >::type C_i(C_iSEXP);
    Rcpp::traits::input_parameter< MatrixXd& >::type C_prob(C_probSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type S_i(S_iSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const MatrixXd >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const MatrixXd >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const MatrixXd >::type psi(psiSEXP);
    update_Ci(itt, C_i, C_prob, S_i, Z, X, Y, alpha, beta, theta, psi);
    return R_NilValue;
END_RCPP
}
