# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
update_Ci <- function(itt, C_i, C_prob, S_i, Z, X, Y, alpha, beta, theta, psi) {
    invisible(.Call('HDMrP_update_Ci', PACKAGE = 'HDMrP', itt, C_i, C_prob, S_i, Z, X, Y, alpha, beta, theta, psi))
}

